# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    main_frontend.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
#    app.directory.namer:
#        class: AppBundle\Naming\DirectoryNamer

    app.vich.namer:
        class: AppBundle\Naming\FileNamer